# Generated by Django 6.0.2 on 2026-02-22 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_checklistitem_id_alter_dayreflection_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('health', '💪 Health'), ('spiritual', '✝️ Spiritual'), ('personal', '👤 Personal'), ('work', '💼 Work'), ('finance', '💰 Finance'), ('other', '📦 Other')], default='personal', max_length=30)),
                ('time_of_day', models.CharField(choices=[('morning', '🌅 Morning'), ('afternoon', '☀️ Afternoon'), ('evening', '🌙 Evening'), ('anytime', '🔄 Anytime')], default='anytime', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_logs', to=settings.AUTH_USER_MODEL)),
                ('routine_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='checklist.routinetask')),
            ],
            options={
                'ordering': ['routine_task__order', 'routine_task__created_at'],
                'unique_together': {('routine_task', 'date')},
            },
        ),
    ]
