# Generated by Django 6.0.2 on 2026-02-26 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('weekend', 'Weekend'), ('gym', 'Gym Day')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='💪', max_length=10)),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
            },
        ),
    ]
